# Generated by Django 3.1 on 2022-04-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='image',
            field=models.ImageField(upload_to='myApp/images'),
        ),
    ]
